#!/usr/bin/env python3

import os, sys, json, imp

config = {}

DEFAULT_MODPATH = "./modules/"

commands = {}
hooks = {}

def load_config():
	global config

	try:
		with open(os.environ["HOME"] + "/.medman/config.json", "r") as c:
			config = json.loads(c.read())
	except:
		print("No config file ~/.medman/config.json found!")
		exit(1)

	# Define required data in the config file here
	fail = False
	if "path" not in config.keys():
		print("Path not specified in config file!")
		fail = True

	if fail:
		exit(1)

# TODO: Write this, verify the proper modules exist
def check_module(module):
	return True


def load_modules():
	def load(path):
		global commands
		global hooks
		global config

		mods = []
		for f in os.listdir(path):
			if f[-3:] == ".py":
				file, pathname, desc = imp.find_module(path + "/" + f[:-3])
				mod = imp.load_module(f[:-3], file, pathname, desc)
				if check_module(mod):
					mods.append(mod)

		for m in mods:
			commands = {}
			
			for d in dir(m):
				if d.startswith("medman_"):
					commands[d.replace("medman_","")] = eval("m." + d) # TODO: Check for conflictions?
				elif d == "hooks":
					for k in m.hooks.keys():
						if k not in hooks.keys():
							hooks[k] = []
						hooks[k].append(m.hooks[k])
		config["hooks"] = hooks


	if "modulepath" in config.keys():
		load(config["modulepath"])
	else:
		load(DEFAULT_MODPATH)


def main():
	# TODO: Handle more in this?

	if len(sys.argv) < 2:
		print(commands.keys()) # TODO: Make default output prettier
		exit(0)
	commands[sys.argv[1]](config, commands, sys.argv[2:])



if __name__ == "__main__":
	load_config()
	load_modules()
	main()
